#!/bin/sh
#
# make_shlib : creates a shareable form of the NAG Fortran Library
#
# $non_shareables call user-supplied routines with fixed names
non_shareables="e04cgyt.o e04dezt.o e04ebzt.o e04fdft.o e04fdyt.o e04gcft.o \
                e04gczt.o e04geft.o e04hfft.o e04hfzt.o e04jaft.o e04kaft.o \
                e04kcft.o e04laft.o"
#
usage()
{
   echo " The specification of the make_shlib script is "
   echo ""
   echo "      make_shlib [ -n | -b | -e | -u ]"
   echo " "
   echo " Use -n to create a shareable library from the standard"
   echo " NAG library (libnag.a)."
   echo ""
   echo " Use -b to create a shareable library from the standard"
   echo " NAG library (libnag.a) for use with AIX BLAS."
   echo ""
   echo " Use -e to create a shareable library from the standard"
   echo " NAG library (libnag.a) for use with ESSL."
   echo ""
   echo " Use -u to create a shareable library from the underscore"
   echo " appended NAG library (libnag_u.a)"
   exit
}
#
# (1) If no options given, print specification
#
if test $# -ne 1
then
   usage
fi
#
# (2) Check option and set variables (libraries, objects  and export files)
#
case $1 in
   -u)
       oldlib=../libnag_u.a
       newlib=libnag_u_sh.a
       exfile=libnag_u.exp ;;
   -n) 
       oldlib=../libnag.a
       newlib=libnag_sh.a
       exfile=libnag.exp ;;
   -b)
       oldlib=../libnag.a
       newlib=libnag_b_sh.a
       othlib=-lblas
       exfile=libnag_for_blas.exp
       objdir=../source/use_aix_blasobj ;;
   -e)
       oldlib=../libnag.a
       newlib=libnag_e_sh.a
       othlib='-lessl -lblas'
       exfile=libnag_for_essl.exp
       objdir=../source/use_esslobj ;;
   -help ) usage ;;
   *     ) echo "$0: Invalid option: $1" ; usage ;;
esac
#
# (3) Test that we can proceed
#
if test ! -r $oldlib
then
   echo " Cannot read non-shared library $oldlib   Quitting"
   exit
fi
#
# (4) Copy requested library and remove non-shareable objects
#
echo " Copying $oldlib"
cp $oldlib libtemp.a
chmod 644 libtemp.a
#
# (5) Replace some BLAS+LAPACK routines with routines without ENTRY points
case $1 in
   -b|-e) if test ! -d $objdir
          then
             echo " Cannot locate replacement objects in $objdir"
             rm libtemp.a
             exit
          fi
          echo " Replacing NAG BLAS+LAPACK routines"
          ar r libtemp.a $objdir/*
          ;;
      *)  ;;
esac
#
# (6) Extract $non_shareables
echo " Extracting objects that cannot be made shareable"
if [ ! -d objects ]
then
  mkdir objects
fi
cd objects
ar x ../libtemp.a $non_shareables
cd ..
ar d libtemp.a $non_shareables
#
# (7) Create shareable object shrsub.o
#
echo " Creating shareable object"
xlf -o shrsub.o -bE:$exfile -bM:SRE $othlib libtemp.a -e_nostart
#
# (8) Create new shareable library using shrsub.o and non-shareable objects
#
echo " Placing shareable object in an archive"
cd objects
ar ql ../libtemp_sh.a ../shrsub.o $non_shareables
cd ..
#
# (9) Tidy
#
mv libtemp_sh.a ../$newlib
rm libtemp.a
rm -r objects
rm shrsub.o
