#!/bin/sh
# Script runs all example tests
#
CMDNAM=`basename $0`
usage()
{
   echo "Usage : ./$CMDNAM -n|-e|-b|-u [-s]"
   echo " options are positional (second is optional) :"
   echo "    -n|-e|-b|-u : use NAG BLAS | ESSL BLAS | AIX BLAS | underscore appended"
   echo "        -s      : use shared lib."

}
#
case $# in
    1) case $1 in
          -n|-e|-b|-u) ;;
               *     ) usage ; exit ;;
       esac
       ;;
    2) case $2 in
          -s) ;;
           *) usage ; exit ;;
       esac
       ;;
    *) usage ; exit ;;
esac
#
runex $* 'a02*'
runex $* 'c02*'
runex $* 'c05*'
runex $* 'c06*'
runex $* 'd01*'
runex $* 'd02*'
runex $* 'd03*'
runex $* 'd04*'
runex $* 'd05*'
runex $* 'e01*'
runex $* 'e02*'
runex $* 'e04*'
runex $* 'f01*'
runex $* 'f02*'
runex $* 'f03*'
runex $* 'f04*'
runex $* 'f05*'
runex $* 'f06*'
runex $* 'f07*'
runex $* 'f08*'
runex $* 'f11*'
runex $* 'g01*'
runex $* 'g02*'
runex $* 'g03*'
runex $* 'g04*'
runex $* 'g05*'
runex $* 'g07*'
runex $* 'g08*'
runex $* 'g10*'
runex $* 'g11*'
runex $* 'g12*'
runex $* 'g13*'
runex $* 'h02*'
runex $* 'h03*'
runex $* 'm01*'
runex $* 'p01*'
runex $* 's01*'
runex $* 's07*'
runex $* 's09*'
runex $* 's10*'
runex $* 's11*'
runex $* 's13*'
runex $* 's14*'
runex $* 's15*'
runex $* 's17*'
runex $* 's18*'
runex $* 's19*'
runex $* 's20*'
runex $* 's21*'
runex $* 'x02*'
runex $* 'x03*'
runex $* 'x04*'
runex $* 'x05*'
