      DOUBLE PRECISION FUNCTION X02AHF(X)
C     MARK 9 RELEASE. NAG COPYRIGHT 1981.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     * MAXIMUM ARGUMENT FOR SIN AND COS *
C     RETURNS THE LARGEST POSITIVE REAL NUMBER MAXSC SUCH THAT
C     SIN(MAXSC) AND COS(MAXSC) CAN BE SUCCESSFULLY COMPUTED
C     BY THE COMPILER SUPPLIED SIN AND COS ROUTINES.
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION                 X
C      DOUBLE PRECISION X02CON
C      DATA X02CON /Z'4690000000000000' /
C     .. Executable Statements ..
C      X02AHF = X02CON
      X02AHF = 1.7976931348623157D+308
C     DBL_MAX ??
      RETURN
      END
