      DOUBLE PRECISION FUNCTION X02ALF()
C     MARK 12 RELEASE. NAG COPYRIGHT 1986.
C
C     RETURNS  (1 - B**(-P)) * B**EMAX  (THE LARGEST POSITIVE MODEL
C     NUMBER)
C
C      DOUBLE PRECISION X02CON
      INTEGER X02BHF, X02BJF , X02BLF
C      DATA X02CON /Z'7FEFFFFFFFFFFFFF' /
C     .. Executable Statements ..
C      X02ALF = X02CON
      X02ALF = (DBLE(X02BHF())**X02BJF() - 1.D0) 
     &            * DBLE(X02BHF())**(X02BLF() - X02BJF())
C     DBL_MAX
      RETURN
      END
