#!/bin/sh
#
# Script differences a single example program's results
#
CMDNAM=`basename $0`
usage()
{
   echo "Usage : ./$CMDNAM directory  routine_name"
   echo "   directory is one of newresults|newresults_b|newresults_e|newresults_u"
   echo "                    newresults_sh|newresults_b_sh|newresults_e_sh|newresults_u"
}
#
case $# in
   2) ;;
   *) usage ; exit ;;
esac
#
MASTER=results
CHECK=$1
#
if [ ! -d ../examples/$CHECK ]
then
   echo " ../examples/$CHECK does not exist" ; exit
fi
#
if [ ! -d ../examples/diffs ]
then
  mkdir ../examples/diffs
fi
cd ../examples
tr '[a-z]' '[A-Z]' < ${MASTER}/${2}e.r | \
sed -e 's/D+/E+/g' -e 's/D-\([0-9]\)/E-\1/g' -e 's/\(()\)/ \1/g' > tmp1
tr '[a-z]' '[A-Z]' < ${CHECK}/${2}e.r | \
sed -e 's/D+/E+/g' -e 's/D-\([0-9]\)/E-\1/g' -e 's/\(()\)/ \1/g' > tmp2
diff -b tmp1 tmp2 > diffs/${2}e.x
rm tmp1 tmp2
if [ ! -s diffs/${2}e.x ]
then
   rm diffs/${2}e.x
fi
